### ISSUE TITLE
Support interlaced video

### ISSUE THREAD

**Issue by tvasenin** [dubhater/vapoursynth-fillborders#3]
If video has `_FieldBased` property, honor it and fill lines using the neighbor line(s) only from the corresponding field.

**Comment by dubhater** [comment]
Any chance you could insert coin? https://ko-fi.com/bitterblue

**Comment by tvasenin** [comment]
@dubhater Done :)

**Comment by dubhater** [comment]
Thank you! I'll get to it.

**Comment by dubhater** [comment]
It's done, but it's off by default because I don't want to change the behaviour of any existing scripts. You'll have to pass "interlaced=-1" to make it look at the _FieldBased property.
